CREATE TYPE "CatType" AS ENUM (
  'Entrata',
  'Uscita'
);

CREATE TYPE "TranStatus" AS ENUM (
  'Singolo',
  'Ricorrente'
);

CREATE TYPE "RecurrenceType" AS ENUM (
  'Ogni mese',
  'Ogni anno'
);

CREATE TABLE "Users" (
  "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "admin" boolean
);

CREATE TABLE "Category" (
  "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "type" "CatType"
);

CREATE TABLE "Account" (
  "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "need_admin" boolean,
  "name" varchar(32),
  "goal" varchar(128),
  "initial_balance" float(2),
  "in_tot" boolean
);

CREATE TABLE "Transactions" (
  "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date,
  "type" "CatType",
  "status" "TranStatus",
  "amount" float(2),
  "description" varchar(256),
  "account_id" int,
  "category_id" int,
  "user_id" int
);

CREATE TABLE "Recurring_Transactions" (
  "ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(32),
  "recursive" "RecurrenceType",
  "deadline" int,
  "type" "CatType",
  "status" "TranStatus",
  "amount" float(2),
  "description" varchar(256),
  "account_id" int,
  "category_id" int,
  "user_id" int
);

COMMENT ON COLUMN "Users"."ID" IS 'ID Progressivo';

COMMENT ON COLUMN "Users"."name" IS 'Nome utente';

COMMENT ON COLUMN "Users"."admin" IS 'Indica se l utente ha permessi di admin';

COMMENT ON COLUMN "Category"."ID" IS 'ID Progressivo';

COMMENT ON COLUMN "Category"."name" IS 'Nome della categoria (es. Cibo, Trasporti)';

COMMENT ON COLUMN "Category"."type" IS 'Specifica se la categoria è una Entrata o una Uscita';

COMMENT ON COLUMN "Account"."ID" IS 'ID Progressivo';

COMMENT ON COLUMN "Account"."need_admin" IS 'Indica se l account richiede permessi di admin';

COMMENT ON COLUMN "Account"."name" IS 'Nome dell account (es. Conto Corrente)';

COMMENT ON COLUMN "Account"."goal" IS 'Obbiettivo finanziario';

COMMENT ON COLUMN "Account"."initial_balance" IS 'Saldo iniziale';

COMMENT ON COLUMN "Account"."in_tot" IS 'Indica se includere nel calcolo del saldo totale';

COMMENT ON COLUMN "Transactions"."ID" IS 'ID Progressivo (Primary Key)';

COMMENT ON COLUMN "Transactions"."date" IS 'Data della transazione';

COMMENT ON COLUMN "Transactions"."type" IS 'Tipo di transazione (Entrata o Uscita)';

COMMENT ON COLUMN "Transactions"."status" IS 'Stato (Singolo o Ricorrente)';

COMMENT ON COLUMN "Transactions"."amount" IS 'Importo della transazione';

COMMENT ON COLUMN "Transactions"."account_id" IS 'ID dell account associato';

COMMENT ON COLUMN "Transactions"."category_id" IS 'ID della categoria associata';

COMMENT ON COLUMN "Transactions"."user_id" IS 'ID dell utente che ha effettuato la transazione';

COMMENT ON COLUMN "Recurring_Transactions"."ID" IS 'ID Progressivo';

COMMENT ON COLUMN "Recurring_Transactions"."name" IS 'Nome per identificare la ricorrenza (es. Affitto)';

COMMENT ON COLUMN "Recurring_Transactions"."recursive" IS 'Frequenza della transazione';

COMMENT ON COLUMN "Recurring_Transactions"."deadline" IS 'Numero di rate o ripetizioni totali';

ALTER TABLE "Transactions" ADD FOREIGN KEY ("account_id") REFERENCES "Account" ("ID");

ALTER TABLE "Transactions" ADD FOREIGN KEY ("category_id") REFERENCES "Category" ("ID");

ALTER TABLE "Transactions" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("ID");

ALTER TABLE "Recurring_Transactions" ADD FOREIGN KEY ("account_id") REFERENCES "Account" ("ID");

ALTER TABLE "Recurring_Transactions" ADD FOREIGN KEY ("category_id") REFERENCES "Category" ("ID");

ALTER TABLE "Recurring_Transactions" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("ID");
